### ISSUE TITLE
bad pad value

### ISSUE THREAD

**Issue by SteveZman** [duncs/clusterssh#108]
Am working on building a Linux Mint laptop and need to use clusterssh on a daily basis.  When testing, I get the following error:

bad pad value "3m": must be positive screen distance at /usr/lib/x86_64-linux-gnu/perl5/5.22/Tk/Widget.pm line 1218.
 at /usr/lib/x86_64-linux-gnu/perl5/5.22/Tk/Widget.pm line 203.

Can anyone help me determine the issue and correct it?  I have been using clusterssh on another laptop with no issues.

Thanks in Advance,
Steve

**Comment by duncs** [comment]
Can you check your .clusterssh/config file to look if there is a value '3' in there that should be followed by a comma but has a typo using an 'm' instead?
Which version of ClusterSSH is this?
  Duncs
    On Thursday, 5 April 2018, 18:05:29 BST, SteveZman <notifications@github.com> wrote:  
 
 
Am working on building a Linux Mint laptop and need to use clusterssh on a daily basis. When testing, I get the following error:

bad pad value "3m": must be positive screen distance at /usr/lib/x86_64-linux-gnu/perl5/5.22/Tk/Widget.pm line 1218.
at /usr/lib/x86_64-linux-gnu/perl5/5.22/Tk/Widget.pm line 203.

Can anyone help me determine the issue and correct it? I have been using clusterssh on another laptop with no issues.

Thanks in Advance,
Steve

**Comment by SteveZman** [comment]
I reviewed the config file – No “3m” entries
Clusterssh version – 4.05

Thanks for the prompt response!

Steve

**Comment by duncs** [comment]
Steve,
Can you run 'cssh -e {hostname}' to see if a single host works, and also gather all the output from 'cssh --debug 4 {hostname}' and send it to me?
Thanks
  Duncs
    On Monday, 9 April 2018, 19:46:30 BST, SteveZman <notifications@github.com> wrote:  
 
 I reviewed the config file – No “3m” entries
Clusterssh version – 4.05

Thanks for the prompt response!

Steve

**Comment by alvin123** [comment]
Hi, duncs,
I have exact the same issue and look for help to fix it. my env are:
Fedora 29
clusterssh-4.13.2-4.fc29.noarch
thanks.

**Comment by duncs** [comment]
Can you run clusterssh with one host under debug using `cssh --debug 4 ....` and send me the output?  This may help me track down where the issue is

**Comment by duncs** [comment]
This appears to be a bug in Tk 804.034 when using Tk::Dialog- using 804.033 on my Debian system works without issue, but using 804.034 on FC29 gives the error.

I will code a work around by using Tk::DialogBox instead as this seems to work on FC29 without issue.

**Comment by duncs** [comment]
Please grab the latest code from the repo and try it out to ensure the problem is fixed for you

**Comment by alvin123** [comment]
the updated version worked like a charm.   Very appreciate for the help!

**Comment by duncs** [comment]
Thanks for confirming.  I'll make as closed when I make the next formal release.

**Comment by fregger65** [comment]
I'm still having this problem on Ubuntu 18.04 LTS in my virtual machines (Vmplayer). On the host however (also 18.04 LTS) it works just fine. I really need this to work in my virtual machines. Is there anyting I can do to fix this?

**Comment by duncs** [comment]
Can you confirm what versions of Tk and ClusterSSH you have installed?

**Comment by fregger65** [comment]
Hi duncs,
That would be tk/bionic,now 8.6.0+9 amd64 [installed] and clusterssh/bionic,bionic,now 4.13-1 all [installed] both on the host (working) and the virtual machine (not working).

**Comment by duncs** [comment]
Thanks for the update
